version: '3.4'

services:
  eureka-server:
    image: mateussss/eureka-server:1.0.0
    ports: 
      - 8761:8761
    expose:
      - 8761
    networks:
      - hr-system
  
  api-gateway:
    image: mateussss/api-gateway:1.0.0
    ports:
      - 8765:8765
    expose:
      - 8765
    depends_on:
      - eureka-server
    environment:
      - EUREKA_URL=http://eureka-server:8761/eureka
    networks:
      - hr-system
  
  user-api:
    image: mateussss/user-api:1.0.0
    ports: 
      - "8080:8080"
    depends_on:
      - eureka-server
      - api-gateway
    environment:
      - EUREKA_URL=http://eureka-server:8761/eureka
    networks:
      - hr-system
      
  payroll-api:
    image: mateussss/payroll-api:1.0.0
    ports: 
      - "8100:8100"
    depends_on:
      - eureka-server
      - api-gateway
      - user-api
    environment:
      - PORT=8100
      - EUREKA_URL=http://eureka-server:8761/eureka
    networks:
      - hr-system

networks:
  hr-system:
    driver: bridge